// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQQWtz7kUT806aIl0KusH1P88GQeDcGS0',
    appId: '1:383854855156:web:f4ba32f3d3eb9fb786afa1',
    messagingSenderId: '383854855156',
    projectId: 'chatterapp-b9e5b',
    authDomain: 'chatterapp-b9e5b.firebaseapp.com',
    storageBucket: 'chatterapp-b9e5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbva6chSGcbflCbJHBATSBN7xzupirvUE',
    appId: '1:383854855156:android:613a1c0bde635c9186afa1',
    messagingSenderId: '383854855156',
    projectId: 'chatterapp-b9e5b',
    storageBucket: 'chatterapp-b9e5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBHdLbfVZQhjE5KbAPkwNoVRSa4ETSU8A',
    appId: '1:383854855156:ios:ad52073e8b05875686afa1',
    messagingSenderId: '383854855156',
    projectId: 'chatterapp-b9e5b',
    storageBucket: 'chatterapp-b9e5b.firebasestorage.app',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBHdLbfVZQhjE5KbAPkwNoVRSa4ETSU8A',
    appId: '1:383854855156:ios:ad52073e8b05875686afa1',
    messagingSenderId: '383854855156',
    projectId: 'chatterapp-b9e5b',
    storageBucket: 'chatterapp-b9e5b.firebasestorage.app',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQQWtz7kUT806aIl0KusH1P88GQeDcGS0',
    appId: '1:383854855156:web:d5cee2a7361cb5b486afa1',
    messagingSenderId: '383854855156',
    projectId: 'chatterapp-b9e5b',
    authDomain: 'chatterapp-b9e5b.firebaseapp.com',
    storageBucket: 'chatterapp-b9e5b.firebasestorage.app',
  );
}
